### PR TITLE
v1.0.1

### PR DESCRIPTION
**Pull request by betzrhodes**
Updated for compatibility with Assist Now
- Removed Assist Now ACK from parser (this code is now included in Assist Now Library)
- Added checks and errors for methods that would cause conflicts with Assist Now

### CODE REVIEW

**Review by smittytone — COMMENTED** [review]
Because of the removal of 0x1360 MGA_ACK messages from Parser, this release is technically is a breaking-change update, so we _ought_ to bump this to 2.0.0. Is it actually worth it since we've only just released this? I don't know; what do you folks think?

**Comment by smittytone** [comment]
I've also removed the MON_VER information from the Parser Read Me, but added invitations to use the UBloxAssistNow library for this and MGA_ACK instead. Let me know if it needs to go back in for some reason; I've kept the removed text.

**Comment by betzrhodes** [comment]
> Because of the removal of 0x1360 MGA_ACK messages from Parser, this release is technically is a breaking-change update, so we _ought_ to bump this to 2.0.0. Is it actually worth it since we've only just released this? I don't know; what do you folks think?

Agree I will update to 2.0.0

**Comment by betzrhodes** [comment]
> I've also removed the MON_VER information from the Parser Read Me, but added invitations to use the UBloxAssistNow library for this and MGA_ACK instead. Let me know if it needs to go back in for some reason; I've kept the removed text.

This is incorrect. The UBloxAssistNow library doesn't parse the MON_VER payload. The UBloxAssistNow library registers a handler for incoming MON_VER messages and has a method that returns the raw payload from the u-blox. The parser is still needed if the user would like to parse the u-blox payload. Please add this back to the docs.

The MGA_ACK has been removed from the parser to avoid duplicated code and to keep UBloxAssistNow from depending on this parser. The MGA_ACK message is needed for the core functionality in the UBloxAssistNow library - if the user would like handle MGA ACKs then they should not be using UBloxAssistNow library. There is no way to bubble up the hundreds of acks in any meaningful way so UBloxAssistNow will not have a getter for this payload. Since users can add to the parser table easily I do not see any issues removing this function from the parser and I would prefer not to highlight it's removal. I think this will only add confusion for users.

**Review by smittytone — APPROVED** [review]

**Review by ppetrosh — APPROVED** [review]

**Pull request merged**
